name: Deploy to Wikipedia (main branch)

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install deploy dependencies
        run: |
          pip install mwparserfromhell>=0.5.0 pywikibot
          npm ci

      - name: Build
        run: npm run build

      - name: Run deploy script
        env:
          BOT_NAME: ${{ secrets.BOT_NAME }}
          BOT_PASS: ${{ secrets.BOT_PASS }}
        run: |
          echo "('Xiplus', BotPassword('${BOT_NAME}', '${BOT_PASS}'))" > user-password.py
          chmod 600 user-password.py
          python3 deploy.py --file dist/unblock-zh-helper.iife.js --target User:Xiplus/js/unblock-zh-helper/unblock-zh-helper.iife.js --summary "Deploying revision ${GITHUB_SHA}"
          python3 deploy.py --file dist/style.css --target User:Xiplus/js/unblock-zh-helper/style.css --summary "Deploying revision ${GITHUB_SHA}"
